name: Build Montainer Image

on:
    push:
        paths:
            - 'versions.json'
    workflow_dispatch:

jobs:
    version-update-check:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code from the GitHub repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Check if the versions.json file has been updated
            - name: Check Updated Versions
              id: check-versions
              run: |
                git fetch origin ${{ github.event.before }}:${{ github.event.before }} 
                git diff ${{ github.event.before }} ${{ github.sha }} -- versions.json > changes.diff
                PREVIEW_UPDATED=$(grep -c '"preview":' changes.diff || true)
                STABLE_UPDATED=$(grep -c '"stable":' changes.diff || true)
                echo "::set-output name=preview_updated::$PREVIEW_UPDATED"
                echo "::set-output name=stable_updated::$STABLE_UPDATED"

    
    