name: Build Montainer (Stable) Image

on:
    push:
        paths:
            - 'Dockerfile'
            - 'versions/stable.txt'
            - '.github/workflows/build-montainer-stable-image.yaml'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code from GitHub repository
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            
            
            - name: Download and Extract Minecraft Server
              run: |
                python3 -m pip install --upgrade pip
                python3 -m pip install requests==2.31.0
                python3 scripts/download_minecraft_server.py --type=stable

            - name: Build frontend web static
              run: |
                cd web/frontend
                npm install
                npm run build

            - name: Fetch Versions
              run: |
                echo "STABLE_VERSION=$(cat versions/stable.txt)" >> $GITHUB_ENV
            
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.PAT }}

            - name: Build Montainer (Stable) Image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: |
                    ghcr.io/wasinuddy/montainer-stable:latest
                    ghcr.io/wasinuddy/montainer-stable:${{ env.STABLE_VERSION }}
                platforms: linux/amd64
                
