name: Fetch Minecraft Server Version

# This workflow is triggered daily and can also be manually triggered
on:
    schedule:
        - cron: '0 0 * * *' # Scheduled to run every day at midnight
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    fetch-version:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code from the GitHub repository
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.PAT }}

            # Setup Python environment
            - name: Setup Python Environment
              uses: actions/setup-python@v4
              with:
                python-version: 3.11

            # Install Chromium and necessary dependencies
            - name: Install Chromium and Dependencies
              run: |
                sudo apt purge --remove google-chrome-stable -y
                sudo apt purge --remove chromium-browser -y
                sudo apt autoremove && sudo apt autoclean -y
                sudo rm -rf /usr/bin/chromium
                sudo apt install chromium-browser -y
                chromium-browser --product-version
                pip install selenium

            # Execute Python script to fetch the latest Minecraft server version
            - name: Fetch Minecraft Server Version
              run: |
                python scripts/fetch_version.py | while IFS='=' read -r key value; do
                    if [ -n "$key" ] && [ -n "$value" ]; then
                        echo "$key=$value" >> $GITHUB_ENV
                    fi
                done

            # Store the fetched stable version and commit the changes
            - name: Store Fetched Stable Version and Commit Changes
              run: |
                echo $STABLE_VERSION > versions/stable.txt
                if git diff --exit-code; then
                  echo "No changes detected in stable version."
                else
                  git add versions/stable.txt
                  git commit -m "Update stable version with latest Minecraft server version"
                  git push
                fi
              shell: bash

            # Store the fetched preview version and commit the changes
            - name: Store Fetched Preview Version and Commit Changes
              run: |
                echo $PREVIEW_VERSION > versions/preview.txt
                if git diff --exit-code; then
                  echo "No changes detected in preview version."
                else
                  git add versions/preview.txt
                  git commit -m "Update preview version with latest Minecraft server version"
                  git push
                fi
              shell: bash